<a href="https://colab.research.google.com/github/JingYang06522/DSTest/blob/main/clean_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("malaysia_house_price_data_2025.csv")

print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (2000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Township      2000 non-null   object
 1   Area          2000 non-null   object
 2   State         2000 non-null   object
 3   Tenure        2000 non-null   object
 4   Type          2000 non-null   object
 5   Median_Price  2000 non-null   float64
 6   Median_PSF    2000 non-null   float64
 7   Transactions  2000 non-null   int64
dtypes: float64(2), int64(1), object(5)
memory usage: 125.1+ KB

In [ ]:
df[['Median_Price', 'Median_PSF', 'Transactions']].describe().round(2)

       Median_Price  Median_PSF  Transactions
count       2000.00     2000.00       2000.00
mean      490685.41      328.86         28.09
std       468632.21      193.28         37.70
min        27049.00       38.00         10.00
25%       269950.00      201.00         12.00
50%       390000.00      293.00         16.00
75%       573500.00      412.00         28.00
max     11420500.00     3017.00        593.00

In [ ]:
df.isnull().sum()

Township        0
Area            0
State           0
Tenure          0
Type            0
Median_Price    0
Median_PSF      0
Transactions    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,Tasek Gelugor,Penang,Freehold,Terrace House,331800.0,304.0,593
1,BANDAR PUTRA,Kulai,Johor,Freehold,"Cluster House, Terrace House",590900.0,322.0,519
2,TAMAN LAGENDA TROPIKA TAPAH,Chenderiang,Perak,Freehold,Terrace House,229954.0,130.0,414
3,SCIENTEX JASIN MUTIARA,Bemban,Melaka,Freehold,Terrace House,255600.0,218.0,391
4,TAMAN LAGENDA AMAN,Tapah,Perak,Leasehold,Terrace House,219300.0,168.0,363

In [ ]:
display((df[['Median_Price', 'Median_PSF', 'Transactions']] <= 0).sum())

Median_Price    0
Median_PSF      0
Transactions    0
dtype: int64

In [ ]:
categorical_columns = ['Township', 'Area', 'State', 'Tenure', 'Type']

for col in categorical_columns:
    df[col] = df[col].astype(str).str.strip().str.upper()

print("Categorical values standardized")

Categorical values standardized

In [ ]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,TASEK GELUGOR,PENANG,FREEHOLD,TERRACE HOUSE,331800.0,304.0,593
1,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,"CLUSTER HOUSE, TERRACE HOUSE",590900.0,322.0,519
2,TAMAN LAGENDA TROPIKA TAPAH,CHENDERIANG,PERAK,FREEHOLD,TERRACE HOUSE,229954.0,130.0,414
3,SCIENTEX JASIN MUTIARA,BEMBAN,MELAKA,FREEHOLD,TERRACE HOUSE,255600.0,218.0,391
4,TAMAN LAGENDA AMAN,TAPAH,PERAK,LEASEHOLD,TERRACE HOUSE,219300.0,168.0,363

In [ ]:
for col in categorical_columns:
    print(col)
    print("Number of unique values:", df[col].nunique())
    print("================================\n")

Township
Number of unique values: 1917
================================

Area
Number of unique values: 303
================================

State
Number of unique values: 16
================================

Tenure
Number of unique values: 4
================================

Type
Number of unique values: 46
================================

In [ ]:
multiple_area = df['Area'].str.contains(',', regex=False)
print("Records with multiple area values:", multiple_area.sum())

Records with multiple area values: 0

In [ ]:
multiple_state = df['State'].str.contains(',', regex=False)
print("Records with multiple state values:", multiple_state.sum())

Records with multiple state values: 0

In [ ]:
multiple_tenure = df['Tenure'].astype(str).str.contains(',', regex=False)
print("Records with multiple tenure values:", multiple_tenure.sum())

Records with multiple tenure values: 58

In [ ]:
tenure_combinations = df.loc[multiple_tenure, 'Tenure'].value_counts()
print(tenure_combinations)

Tenure
FREEHOLD, LEASEHOLD    31
LEASEHOLD, FREEHOLD    27
Name: count, dtype: int64

In [ ]:
df = df[~multiple_tenure].copy()
print("Remove multiple-tenure records")
print("Dataset shape after remove multiple-tenure records:", df.shape)
print("Remaining multiple-tenure records:", df['Tenure'].astype(str).str.contains(',', regex=False).sum())

Remove multiple-tenure records
Dataset shape after remove multiple-tenure records: (1942, 8)
Remaining multiple-tenure records: 0

In [ ]:
multiple_type = df['Type'].str.contains(',', regex=False)
print("Records with multiple type values:", multiple_type.sum())

Records with multiple type values: 350

In [ ]:
type_combinations = df.loc[multiple_type, 'Type'].value_counts()
print(type_combinations)

Type
TERRACE HOUSE, SEMI D                       97
SEMI D, TERRACE HOUSE                       80
TERRACE HOUSE, CLUSTER HOUSE                31
CLUSTER HOUSE, TERRACE HOUSE                22
TERRACE HOUSE, BUNGALOW                     21
BUNGALOW, TERRACE HOUSE                     18
BUNGALOW, SEMI D                            13
TERRACE HOUSE, TOWN HOUSE                    8
SEMI D, BUNGALOW                             8
TOWN HOUSE, TERRACE HOUSE                    7
CLUSTER HOUSE, SEMI D                        6
SEMI D, CLUSTER HOUSE                        4
CLUSTER HOUSE, TERRACE HOUSE, SEMI D         3
BUNGALOW, TERRACE HOUSE, SEMI D              3
TERRACE HOUSE, SEMI D, BUNGALOW              3
SEMI D, TOWN HOUSE, TERRACE HOUSE            2
FLAT, APARTMENT                              2
TERRACE HOUSE, BUNGALOW, SEMI D              2
TERRACE HOUSE, SEMI D, TOWN HOUSE            2
SEMI D, TERRACE HOUSE, BUNGALOW              2
BUNGALOW, TOWN HOUSE                         1
SEMI D, CLUSTER HOUSE, BUNGALOW              1
SEMI D, TERRACE HOUSE, CLUSTER HOUSE         1
TOWN HOUSE, TERRACE HOUSE, SEMI D            1
FLAT, CONDOMINIUM                            1
TOWN HOUSE, BUNGALOW, TERRACE HOUSE          1
APARTMENT, FLAT                              1
TOWN HOUSE, SEMI D                           1
SEMI D, BUNGALOW, TERRACE HOUSE              1
TOWN HOUSE, SEMI D, TERRACE HOUSE            1
CONDOMINIUM, SERVICE RESIDENCE               1
CLUSTER HOUSE, BUNGALOW                      1
BUNGALOW, SEMI D, TERRACE HOUSE              1
SEMI D, TERRACE HOUSE, TOWN HOUSE            1
CLUSTER HOUSE, TOWN HOUSE, TERRACE HOUSE     1
SEMI D, TOWN HOUSE                           1
Name: count, dtype: int64

In [ ]:
df['Type_Standardized'] = df['Type'].apply(lambda x: ', '.join(sorted([t.strip() for t in x.split(',')])))
type_standardized_combination = df.loc[multiple_type, 'Type_Standardized'].value_counts()
print(type_standardized_combination)

Type_Standardized
SEMI D, TERRACE HOUSE                       177
CLUSTER HOUSE, TERRACE HOUSE                 53
BUNGALOW, TERRACE HOUSE                      39
BUNGALOW, SEMI D                             21
TERRACE HOUSE, TOWN HOUSE                    15
BUNGALOW, SEMI D, TERRACE HOUSE              12
CLUSTER HOUSE, SEMI D                        10
SEMI D, TERRACE HOUSE, TOWN HOUSE             7
CLUSTER HOUSE, SEMI D, TERRACE HOUSE          4
APARTMENT, FLAT                               3
SEMI D, TOWN HOUSE                            2
BUNGALOW, CLUSTER HOUSE, SEMI D               1
CONDOMINIUM, FLAT                             1
BUNGALOW, TOWN HOUSE                          1
BUNGALOW, TERRACE HOUSE, TOWN HOUSE           1
CONDOMINIUM, SERVICE RESIDENCE                1
BUNGALOW, CLUSTER HOUSE                       1
CLUSTER HOUSE, TERRACE HOUSE, TOWN HOUSE      1
Name: count, dtype: int64

In [ ]:
df['Type_Standardized'] = (df['Type_Standardized'].str.split(', '))
df = df.explode('Type_Standardized',ignore_index=True)
df['Type'] = df['Type_Standardized']
df.drop(columns=['Type_Standardized'],inplace=True)
print("Type splitting completed")
print("Remaining multiple type records:",df['Type'].str.contains(',', regex=False).sum())
print("New dataset shape:", df.shape)

Type splitting completed
Remaining multiple type records: 0
New dataset shape: (2318, 8)

In [ ]:
print(df['Type'].value_counts())

Type
TERRACE HOUSE        1226
SEMI D                277
APARTMENT             199
CONDOMINIUM           169
FLAT                  135
SERVICE RESIDENCE      96
CLUSTER HOUSE          93
BUNGALOW               89
TOWN HOUSE             34
Name: count, dtype: int64

In [ ]:
df.head(5)

,Township,Area,State,Tenure,Type,Median_Price,Median_PSF,Transactions
0,SCIENTEX SUNGAI DUA,TASEK GELUGOR,PENANG,FREEHOLD,TERRACE HOUSE,331800.0,304.0,593
1,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,CLUSTER HOUSE,590900.0,322.0,519
2,BANDAR PUTRA,KULAI,JOHOR,FREEHOLD,TERRACE HOUSE,590900.0,322.0,519
3,TAMAN LAGENDA TROPIKA TAPAH,CHENDERIANG,PERAK,FREEHOLD,TERRACE HOUSE,229954.0,130.0,414
4,SCIENTEX JASIN MUTIARA,BEMBAN,MELAKA,FREEHOLD,TERRACE HOUSE,255600.0,218.0,391

In [ ]:
numerical_columns = ['Median_Price', 'Median_PSF', 'Transactions']

for col in numerical_columns:
    Q1 = df.groupby(['State', 'Type'])[col].transform('quantile', 0.25)
    Q3 = df.groupby(['State', 'Type'])[col].transform('quantile', 0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    count_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    lower_3 = Q1 - 3.0 * IQR
    upper_3 = Q3 + 3.0 * IQR
    count_outliers_3 = df[(df[col] < lower_3) | (df[col] > upper_3)]

    print(col)
    print("Number of outliers (1.5 x IQR):", len(count_outliers))
    print("Number of outliers (3.0 x IQR):", len(count_outliers_3))
    print("=======================================\n")

Median_Price
Number of outliers (1.5 x IQR): 115
Number of outliers (3.0 x IQR): 35
=======================================

Median_PSF
Number of outliers (1.5 x IQR): 88
Number of outliers (3.0 x IQR): 14
=======================================

Transactions
Number of outliers (1.5 x IQR): 199
Number of outliers (3.0 x IQR): 92
=======================================

In [ ]:
cleaned_df = df.copy()

outlier_columns = ['Median_Price', 'Median_PSF']

for col in outlier_columns:

    Q1 = cleaned_df.groupby(['State', 'Type'])[col].transform('quantile', 0.25)
    Q3 = cleaned_df.groupby(['State', 'Type'])[col].transform('quantile', 0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 3 * IQR
    upper_bound = Q3 + 3 * IQR

    lower_outliers = (cleaned_df[col] < lower_bound).sum()
    upper_outliers = (cleaned_df[col] > upper_bound).sum()

    cleaned_df[col] = cleaned_df[col].clip(
        lower=lower_bound,
        upper=upper_bound
    )

    print(col)
    print("Lower outliers capped:", lower_outliers)
    print("Upper outliers capped:", upper_outliers)
    print("====================================\n")

Median_Price
Lower outliers capped: 1
Upper outliers capped: 34
====================================

Median_PSF
Lower outliers capped: 1
Upper outliers capped: 13
====================================

In [ ]:
import numpy as np

cleaned_df["Transactions_Log"] = np.log1p(
    cleaned_df["Transactions"]
)

In [ ]:
# Check which values were changed by outlier capping

for col in numerical_columns:
    changed = df.loc[cleaned_df[col] != df[col],
                     ['State', 'Type', col]].copy()

    print(f"\n{col} - Number of changed values: {len(changed)}")
    display(changed.head(20))

Median_Price - Number of changed values: 35

             State               Type  Median_Price
131          JOHOR  SERVICE RESIDENCE     1386800.0
516       SELANGOR        CONDOMINIUM     1269000.0
539          JOHOR      TERRACE HOUSE     1680000.0
564          JOHOR  SERVICE RESIDENCE     2386358.0
579       SELANGOR      CLUSTER HOUSE     2330000.0
687       SELANGOR      TERRACE HOUSE     2400000.0
722         MELAKA      TERRACE HOUSE      685000.0
735       SELANGOR      TERRACE HOUSE     1890000.0
751         PENANG      TERRACE HOUSE     3450000.0
754         MELAKA      TERRACE HOUSE      645000.0
761   KUALA LUMPUR        CONDOMINIUM     2800000.0
805       SELANGOR      TERRACE HOUSE     1875000.0
883          JOHOR               FLAT      250000.0
965         PENANG      TERRACE HOUSE     2200000.0
979   KUALA LUMPUR      TERRACE HOUSE     2500000.0
1034      SELANGOR      TERRACE HOUSE     2550000.0
1035      SELANGOR         TOWN HOUSE     2550000.0
1073  KUALA LUMPUR        CONDOMINIUM     3350000.0
1079      SELANGOR        CONDOMINIUM     1109000.0
1224         SABAH      TERRACE HOUSE     1040000.0

Median_PSF - Number of changed values: 14

             State               Type  Median_PSF
131          JOHOR  SERVICE RESIDENCE      1270.0
442          KEDAH      TERRACE HOUSE       387.0
564          JOHOR  SERVICE RESIDENCE      1055.0
751         PENANG      TERRACE HOUSE      1146.0
753         MELAKA             SEMI D       388.0
858     TERENGGANU             SEMI D       190.0
883          JOHOR               FLAT       438.0
964         PENANG           BUNGALOW       465.0
1087      SELANGOR      TERRACE HOUSE      1071.0
1223         SABAH             SEMI D       537.0
1224         SABAH      TERRACE HOUSE       537.0
1443         KEDAH      TERRACE HOUSE       435.0
1535  KUALA LUMPUR  SERVICE RESIDENCE      3017.0
1711         JOHOR               FLAT        77.0

Transactions - Number of changed values: 92

              State           Type  Transactions
0            PENANG  TERRACE HOUSE           593
1             JOHOR  CLUSTER HOUSE           519
2             JOHOR  TERRACE HOUSE           519
3             PERAK  TERRACE HOUSE           414
4            MELAKA  TERRACE HOUSE           391
5             PERAK  TERRACE HOUSE           363
6             JOHOR         SEMI D           349
7             JOHOR  TERRACE HOUSE           349
8             JOHOR  TERRACE HOUSE           319
9             PERAK  CLUSTER HOUSE           309
10            PERAK  TERRACE HOUSE           309
11           MELAKA  TERRACE HOUSE           301
12         SELANGOR  TERRACE HOUSE           292
13           MELAKA  TERRACE HOUSE           288
14            JOHOR  TERRACE HOUSE           259
15  NEGERI SEMBILAN  TERRACE HOUSE           210
16            JOHOR         SEMI D           203
17            JOHOR  TERRACE HOUSE           203
18            JOHOR  TERRACE HOUSE           202
19            JOHOR  TERRACE HOUSE           195

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
# ==========================================
# Compare Original vs Capped Values
# ==========================================

for col in numerical_columns:

    changed = df[col] != cleaned_df[col]

    comparison = pd.DataFrame({
        'State': df.loc[changed, 'State'],
        'Type': df.loc[changed, 'Type'],
        'Original': df.loc[changed, col],
        'Capped': cleaned_df.loc[changed, col]
    })

    print(f"\n{col}")
    print(f"Number of changed values: {len(comparison)}")

    display(comparison.head(20))

Median_Price
Number of changed values: 35

             State               Type   Original     Capped
131          JOHOR  SERVICE RESIDENCE  1386800.0  1025500.0
516       SELANGOR        CONDOMINIUM  1269000.0  1010000.0
539          JOHOR      TERRACE HOUSE  1680000.0  1477500.0
564          JOHOR  SERVICE RESIDENCE  2386358.0  1025500.0
579       SELANGOR      CLUSTER HOUSE  2330000.0  2312700.0
687       SELANGOR      TERRACE HOUSE  2400000.0  1872875.0
722         MELAKA      TERRACE HOUSE   685000.0   596000.0
735       SELANGOR      TERRACE HOUSE  1890000.0  1872875.0
751         PENANG      TERRACE HOUSE  3450000.0  1536450.0
754         MELAKA      TERRACE HOUSE   645000.0   596000.0
761   KUALA LUMPUR        CONDOMINIUM  2800000.0  2548750.0
805       SELANGOR      TERRACE HOUSE  1875000.0  1872875.0
883          JOHOR               FLAT   250000.0   232750.0
965         PENANG      TERRACE HOUSE  2200000.0  1536450.0
979   KUALA LUMPUR      TERRACE HOUSE  2500000.0  2281500.0
1034      SELANGOR      TERRACE HOUSE  2550000.0  1872875.0
1035      SELANGOR         TOWN HOUSE  2550000.0  1845200.0
1073  KUALA LUMPUR        CONDOMINIUM  3350000.0  2548750.0
1079      SELANGOR        CONDOMINIUM  1109000.0  1010000.0
1224         SABAH      TERRACE HOUSE  1040000.0   733750.0

Median_PSF
Number of changed values: 14

             State               Type  Original   Capped
131          JOHOR  SERVICE RESIDENCE    1270.0   902.00
442          KEDAH      TERRACE HOUSE     387.0   374.00
564          JOHOR  SERVICE RESIDENCE    1055.0   902.00
751         PENANG      TERRACE HOUSE    1146.0   835.25
753         MELAKA             SEMI D     388.0   371.00
858     TERENGGANU             SEMI D     190.0   171.00
883          JOHOR               FLAT     438.0   390.75
964         PENANG           BUNGALOW     465.0   388.00
1087      SELANGOR      TERRACE HOUSE    1071.0  1057.00
1223         SABAH             SEMI D     537.0   364.00
1224         SABAH      TERRACE HOUSE     537.0   491.50
1443         KEDAH      TERRACE HOUSE     435.0   374.00
1535  KUALA LUMPUR  SERVICE RESIDENCE    3017.0  2820.00
1711         JOHOR               FLAT      77.0    93.25

Transactions
Number of changed values: 92

              State           Type  Original  Capped
0            PENANG  TERRACE HOUSE       593   51.00
1             JOHOR  CLUSTER HOUSE       519  310.25
2             JOHOR  TERRACE HOUSE       519  186.00
3             PERAK  TERRACE HOUSE       414   88.00
4            MELAKA  TERRACE HOUSE       391   88.00
5             PERAK  TERRACE HOUSE       363   88.00
6             JOHOR         SEMI D       349  154.00
7             JOHOR  TERRACE HOUSE       349  186.00
8             JOHOR  TERRACE HOUSE       319  186.00
9             PERAK  CLUSTER HOUSE       309   59.50
10            PERAK  TERRACE HOUSE       309   88.00
11           MELAKA  TERRACE HOUSE       301   88.00
12         SELANGOR  TERRACE HOUSE       292  105.00
13           MELAKA  TERRACE HOUSE       288   88.00
14            JOHOR  TERRACE HOUSE       259  186.00
15  NEGERI SEMBILAN  TERRACE HOUSE       210  109.00
16            JOHOR         SEMI D       203  154.00
17            JOHOR  TERRACE HOUSE       203  186.00
18            JOHOR  TERRACE HOUSE       202  186.00
19            JOHOR  TERRACE HOUSE       195  186.00

In [ ]:
# Check the distribution of Transactions

print("Original Transactions:")
display(df["Transactions"].describe())

print("\nTransactions after capping:")
display(cleaned_df["Transactions"].describe())

Original Transactions:

count    2318.000000
mean       29.047023
std        39.463831
min        10.000000
25%        12.000000
50%        17.000000
75%        29.000000
max       593.000000
Name: Transactions, dtype: float64

Transactions after capping:

count    2318.000000
mean       26.509491
std        26.244299
min        10.000000
25%        12.000000
50%        17.000000
75%        29.000000
max       310.250000
Name: Transactions, dtype: float64

In [ ]:
# Check how much Transactions changed

transaction_comparison = pd.DataFrame({
    "Original": df["Transactions"],
    "Capped": cleaned_df["Transactions"]
})

transaction_comparison["Difference"] = (
    transaction_comparison["Original"]
    - transaction_comparison["Capped"]
)

display(
    transaction_comparison
    .sort_values("Difference", ascending=False)
    .head(20)
)

    Original  Capped  Difference
0        593   51.00      542.00
2        519  186.00      333.00
3        414   88.00      326.00
4        391   88.00      303.00
5        363   88.00      275.00
9        309   59.50      249.50
10       309   88.00      221.00
11       301   88.00      213.00
1        519  310.25      208.75
13       288   88.00      200.00
6        349  154.00      195.00
12       292  105.00      187.00
7        349  186.00      163.00
8        319  186.00      133.00
35       164   61.50      102.50
15       210  109.00      101.00
34       165   73.00       92.00
45       141   51.00       90.00
54       135   58.00       77.00
47       140   63.00       77.00

In [ ]:
display(cleaned_df[['Median_Price', 'Median_PSF', 'Transactions']].describe().round(2))

       Median_Price  Median_PSF  Transactions
count       2318.00     2318.00       2318.00
mean      492974.45      324.65         25.99
std       348183.58      180.22         22.97
min        27049.00       38.00         10.00
25%       275450.00      197.00         12.00
50%       400000.00      289.00         17.00
75%       600000.00      413.75         29.00
max      3600000.00     1815.00        175.00

In [ ]:
cleaned_df.to_csv('malaysia_house_price_data_2025_cleaned.csv', index=False)
print("Cleaned dataset exported to 'malaysia_house_price_data_2025_cleaned.csv'")

Cleaned dataset exported to 'malaysia_house_price_data_2025_cleaned.csv'

In [ ]:
df_recheck = pd.read_csv('malaysia_house_price_data_2025_cleaned.csv')

print("Dataset loaded successfully")

print("\nShape:", df_recheck.shape)
print("\nTotal Missing Values:", df_recheck.isnull().sum().sum())
print("\nDuplicate Rows:", df_recheck.duplicated().sum())
print("\nMaximum Values:")
print(df_recheck[['Median_Price', 'Median_PSF', 'Transactions']].max())
print("\nMinimum Values:")
print(df_recheck[['Median_Price', 'Median_PSF', 'Transactions']].min())
print()
for col in categorical_columns:
    print(col)
    print("Number of unique values:", df_recheck[col].nunique())
    print("Blank strings:", (df_recheck[col].astype(str).str.strip() == '').sum())
    print("================================\n")

Dataset loaded successfully

Shape: (2318, 8)

Total Missing Values: 0

Duplicate Rows: 0

Maximum Values:
Median_Price    3600000.0
Median_PSF         1815.0
Transactions        175.0
dtype: float64

Minimum Values:
Median_Price    27049.0
Median_PSF         38.0
Transactions       10.0
dtype: float64

Township
Number of unique values: 1867
Blank strings: 0
================================

Area
Number of unique values: 299
Blank strings: 0
================================

State
Number of unique values: 16
Blank strings: 0
================================

Tenure
Number of unique values: 2
Blank strings: 0
================================

Type
Number of unique values: 9
Blank strings: 0
================================